### ISSUE TITLE
Content Element: Section

### ISSUE THREAD

**Issue by deadlyfingers** [vjrantal/badge-builder#10]
Section with title for progress indicator

**Comment by deadlyfingers** [comment]
@vjrantal will need a slight refactor of client / backend to have an array of arrays

**Comment by liliankasem** [comment]
Just a note: I've put in a '...' icon fab for the section divider in the editor

**Comment by vjrantal** [comment]
@liliankasem: Can you remind me which one we will do first a) score badge per section before user moves to the next section b) score the entire badge at the end? Both are fairly easy to do in the backend, but if we want a) first, I'll introduce a new REST API endpoint to check results per section.

**Comment by liliankasem** [comment]
I think we should score the badge at the end, but we want to accumulate points as we go along. So, we need to check answers at the end of  **every** section so that before they go to the next section they can see if they got it right or wrong and try again. Then at the end of the badge, we get all the section scores together to determine if they got the badge or not.

**Comment by deadlyfingers** [comment]
Done as single array for now - not sure if we need multi-dimensional array here?
